name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clear old dist directory
        run: |
          echo "Clearing old dist directory"
          rm -rf dist/*
          ls -l dist || echo "dist directory does not exist yet"

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          npm install

      - name: Build project
        run: |
          echo "Building project"
          npx webpack --config webpack.config.js --mode production
          echo "Build finished"

      - name: Verify build output
        run: |
          echo "Verifying build output"
          ls -l dist
          ls -l dist/assets/images

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Verify download
        run: |
          echo "Verifying downloaded artifact"
          ls -l dist

      - name: Clean up previous build on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            echo "Cleaning up previous build on server"
            rm -rf /var/www/game/dist/*

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "dist/"
          target: "/var/www/game/dist/"
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: true
          strip_components: 1
          overwrite: true
          tar_dereference: false
          tar_exec: tar
          proxy_port: 22
          proxy_timeout: 30s
          proxy_use_insecure_cipher: false

      - name: Restart Game Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: "~/scripts/start_game_server.sh"
